import * as MailComposer from 'expo-mail-composer';
import { Alert, Linking } from 'react-native';

interface EmailOptions {
  to: string;
  subject: string;
  body: string;
  isHtml?: boolean;
}

interface StudyPlan {
  courseCode: string;
  courseTitle: string;
  modules: Module[];
}

interface Module {
  moduleLabel: string;
  topics: Topic[];
}

interface Topic {
  name: string;
  rating?: number;
  priority?: 'high' | 'medium' | 'low';
  resources?: Resource[];
}

interface Resource {
  url: string;
  type: 'youtube' | 'web' | string;
  title?: string;
}

/**
 * Sends an email using the device's default email client or falls back to MailComposer
 */
export const sendEmail = async (options: EmailOptions): Promise<boolean> => {
  try {
    const { to, subject, body } = options;
    
    // First, try to use the device's default email client
    const emailUrl = `mailto:${to || ''}?subject=${encodeURIComponent(subject || 'Your Study Plan')}&body=${encodeURIComponent(body)}`;
    
    const canOpen = await Linking.canOpenURL(emailUrl);
    if (canOpen) {
      await Linking.openURL(emailUrl);
      return true;
    }
    
    // Fall back to MailComposer if Linking doesn't work
    const isAvailable = await MailComposer.isAvailableAsync();
    if (!isAvailable) {
      Alert.alert('Error', 'No email client available');
      return false;
    }
    
    const result = await MailComposer.composeAsync({
      recipients: to ? [to] : [],
      subject: subject || 'Your Study Plan',
      body: body,
      isHtml: false,
    });
    
    return result.status === 'sent';
  } catch (error) {
    console.error('Error in sendEmail:', error);
    Alert.alert(
      'Email Error', 
      'Failed to open email client. Please make sure you have an email account set up on your device.\n\n' +
      'Error: ' + (error instanceof Error ? error.message : 'Unknown error')
    );
    return false;
  }
};

/**
 * Generates a plain text email body for a study plan
 */
export const generateStudyPlanEmail = (studyPlan: StudyPlan): string => {
  const courseTitle = studyPlan.courseTitle || 'Your Course';
  
  // Create sections for each module
  const moduleSections = studyPlan.modules.map(module => {
    const topicSections = module.topics.map(topic => {
      const rating = topic.rating || 0;
      const status = rating <= 3 ? '⚠️ Needs Attention' : '✅ Comfortable';
      const priority = topic.priority ? `[${topic.priority.toUpperCase()}] ` : '';
      
      // Format resources
      const resources = topic.resources?.map(resource => {
        const type = resource.type === 'youtube' ? '🎥 Video' : '📚 Resource';
        return `  • ${type}: ${resource.title || resource.url}`;
      }).join('\n') || '  • No resources available';
      
      return `
${priority}🔹 ${topic.name}
   Rating: ${rating}/5 (${status})
   Resources:
${resources}`;
    }).join('\n\n');
    
    return `📚 ${module.moduleLabel}${topicSections ? '\n' + topicSections : ''}`;
  }).join('\n\n');
  
  const studyTips = `

💡 STUDY TIPS:
• Start with topics marked as [HIGH] priority
• Focus on topics with ⚠️ Needs Attention first
• Take notes while watching videos
• Test yourself with practice questions
• Review regularly to reinforce learning`;
  
  return `📋 STUDY PLAN: ${courseTitle.toUpperCase()}

${moduleSections}

${studyTips}

---
Generated by StudyBee - Your Learning Companion`;
};
